### ISSUE TITLE
Create GUM tool for managing the project

### ISSUE THREAD

**Issue by asynchroza** [AUBGTheHUB/spa-website-2022#167]

**Comment by asynchroza** [comment]
https://github.com/charmbracelet/gum

**Comment by asynchroza** [comment]
@r-mishev if you want to tackle this, I came up with something you could add to the tool. There is a script called `set_vm_env.sh` which installs all requirements for running the project. You could implement some logic for ssh-ing into the VM and installing the script. Additionally, a good update would be for the script to be trying to log into `root@ip` where ip is fetched as an env variable but if missing, the user is asked to input it.

**Comment by asynchroza** [comment]
Work on this is not finished, do not close the issue

**Comment by r-mishev** [comment]
What more has to be done?
