### ISSUE TITLE
Change color of HackAUBG button in both Desktop and Mobile navbar 

### ISSUE THREAD

**Issue by SuelaCark** [AUBGTheHUB/spa-website-2022#173]
This issue requires to complete the following:
(1) In Mobile navbar, the HackAUBG button color should look more like a gradient (please use the gradient colors - light blue to dark blue - of the HackAUBG button in Desktop navbar as an example)
(2) In Desktop navbar, you need to change the green color of HackAUBG button gradient transition effect to the green color specified by the design.
(3) Make the corners of the navbar anchors on hover effect less sharp/more round

**Comment by LucianAiolos** [comment]
I would like to work on this!

**Comment by LucianAiolos** [comment]
Hey @SuelaCark, almost done except I'm not sure where I can find the design so I can see which green color to use.
