### ISSUE TITLE
Meet the team button is not working in landing section

### ISSUE THREAD

**Issue by asynchroza** [AUBGTheHUB/spa-website-2022#211]

**Comment by r-mishev** [comment]
@asynchroza , is it supposed to redirect to the "About Us" section or to the "Hubbers" carousel?

**Comment by SuelaCark** [comment]
@r-mishev Its suppose to redirect to the Hubbers carousel. While working on this ticket, please also change the "Hubbers" section title to "Meet the team"

**Comment by asynchroza** [comment]
> @r-mishev Its suppose to redirect to the Hubbers carousel. While working on this ticket, please also change the "Hubbers" section title to "Meet the team"

Should it be "Meet the team"? I prefer "Hubbers" honestly, gives us identity.
