### ISSUE TITLE
HackAUBG Hamburger menu/navbar 

### ISSUE THREAD

**Issue by SuelaCark** [AUBGTheHUB/spa-website-2022#222]
Make the mobile navbar for HackAUBG sticky.
Also, when you open the hamburger menu, the menu is in red color. Please change the color to match the webpage's theme (matrix - green, black and white combo).
Additionally, make the hamburger menu color black with same opacity as the HackAUBG Desktop navbar

**Comment by asynchroza** [comment]
Isn't this why we decided to reuse the arrow button (scroll to top)?

**Comment by asynchroza** [comment]
Ooh this is an old issue I actually worked on. Please close it if you deem it done.
