### ISSUE TITLE
HackAUBG Navbar anchor onHover color

### ISSUE THREAD

**Issue by SuelaCark** [AUBGTheHUB/spa-website-2022#230]
Change the HackAUBG anchors onHover color. Currently is dark blue as in the landing page, change it to the green used in the HackAUBG webpage. 
If you don't like how the color combo of white and green looks, you can play around with the onHover effect colors of anchors (white, black, green)

>>> Also fix the the font responsiveness and spacing/padding-right of the "Grading criteria" anchor (issue picture shown below)

**Comment by asynchroza** [comment]
Duplication of #228 , closing this one.

**Comment by SuelaCark** [comment]
Here also fix the the font responsiveness and spacing/padding-right of the "Grading criteria" anchor
![image](https://user-images.githubusercontent.com/77395265/217007391-215efe69-1a77-4dd4-a696-611fdfea3fcb.png)
![image](https://user-images.githubusercontent.com/77395265/217007698-6cce452c-d017-4470-a01b-1a8b58130d9a.png)
