### ISSUE TITLE
Add Hub Logo Favicon to the website

### ISSUE THREAD

**Issue by nikolayninov** [AUBGTheHUB/spa-website-2022#232]

**Comment by Mohammad-Farhan64** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Hub Logo Favicon to the website · Issue #232 · AUBGTheHUB/spa-website-2022</title>

    <link rel="icon" class="js-site-favicon" type="image/svg+xml" href="https://github.githubassets.com/favicons/favicon-dark.svg"></head>
<body>
   
</body>
</html>

**Comment by Mohammad-Farhan64** [comment]
<title>Add Hub Logo Favicon to the website · Issue #232 · AUBGTheHUB/spa-website-2022</title>

      <link rel="icon" class="js-site-favicon" type="image/svg+xml" href="https://github.githubassets.com/favicons/favicon-dark.svg">
