### ISSUE TITLE
Make back-to-the-top button

### ISSUE THREAD

**Issue by SuelaCark** [AUBGTheHUB/spa-website-2022#238]
Create a button for going back to the top of the screen and will be shown all the time in the bottom-right corner.  You can use the hubconf back-to-the-top button as a reference.

**Comment by asynchroza** [comment]
@r-mishev there's an implementation of such a button in the hubconf repo. Maybe check it out and reuse it.

**Comment by asynchroza** [comment]
Here's a link https://github.com/AUBGTheHUB/hub-conf-signup/blob/master/packages/web/src/components/TopBtn.js
