### ISSUE TITLE
Font-size to be the same in all headers

### ISSUE THREAD

**Issue by SuelaCark** [AUBGTheHUB/spa-website-2022#247]
In HackAUBG webpage make sure that all section headers have the same font-size.

**Comment by SuelaCark** [comment]
@MiroGorski Can you please work on this ticket?

**Comment by SuelaCark** [comment]
@MiroGorski Here also check for the responsiveness of each header, meaning to check if the font on mobile will be centered, justified, and dynamic (change depending on the screen width).

**Comment by SuelaCark** [comment]
@MiroGorski As I checked the changes in your branch, I noticed that the font-size is changed incorrectly. 
(1) I have said this in the groupchat and internal hackathons: We don't use pixels (px) for fonts, width, height, etc. This is because the pixels make the page static and then we don't have any responsiveness. Instead we use rem, em (for fonts), % (for padding and margins), vh, vw (for width and height). For example, if we were to merge your branch into master, the header fonts would break the page width and would also be huge for when the website is used in mobile. Please change all the headers to have the same font-size using rem or em. 
(2) In some files you have changed the font-size of the headers only in the media queries (meaning the provided font-size will take effect only on mobile and will look huge -- cuz you used 32 px for the font-size).
(3) You haven't created a Pull Request for these changes. Please open a PR so we can review requested changes in a more proper way.

Please work on the above requested changes^^ @MiroGorski

**Comment by MiroGorski** [comment]
I think all the font sizes are now uniform(2rem) across both mobile and desktop and I also noticed that the FAQ title was not properly aligned so I fixed that as well with the help of Eldi. Ready for review.
