### ISSUE TITLE
Simplify file structure in Grading Criteria Section

### ISSUE THREAD

**Issue by SuelaCark** [AUBGTheHUB/spa-website-2022#248]
Apparently the Grading Criteria Section has separate files for mobile and desktop and most code in both of them is the same. Such thing can be omitted by using **Media Queries**. Please simplify the file structure by having only 1 jsx file and only 1 css file for this section!

**Comment by asynchroza** [comment]
Structure is a bit different between the two versions. It's okay to keep it like that. The only thing I would like is to remove the dots from the classNames in the Desktop version.

**Comment by SuelaCark** [comment]
@override that^^ I want to have only 1 GradingCriteria.jsx file with 1 main div consistent of 4 other divs, each representing a column of the table. I don't want the tags <table><tr><td> to be used. Also, only 1 grading_criteria.css file which will use media queries for desktop-to-mobile responsiveness. Please do not overcomplicate simple code and optimize your code wherever it is possible.
