### ISSUE TITLE
HackAUBG Admin Panel Sections

### ISSUE THREAD

**Issue by nikolayninov** [AUBGTheHUB/spa-website-2022#310]
## Brief description:
Create all the necessary sections in the admin panel for the hackaubg team management
## How to achieve it:
Pages:
- `/admin/hackathon/teams` : should display all hackathon teams with info about the number of current members, name of the team, and the predominant school (e.g. if there are three people from AUBG, one from FMI - you write AUBG on the card) (cards should have see members button which will return `/admin/hackathon/teams/members`)
- `/admin/hackathon/teams/members` : cards with members containing all of their info (similar to the `/admin/members` )
-  `/admin/hackathon/teams/emails` : which fetches all of the participants' emails and renders them on the page as follows (OR just the emails separated by the commas
-

**Comment by asynchroza** [comment]
@nikolayninov @SamuilMladenov open a draft PR so that I can track changes
