### ISSUE TITLE
Update schedule section text

### ISSUE THREAD

**Issue by annakukova** [AUBGTheHUB/spa-website-2022#314]
**The updated schedule is the following:**

Note: This schedule is prone to changes. Hence, check with @SuelaCark before approving and merging PRs that include this ticket.

_**NEW CHANGES IN SATURDAY SCHEDULE**_

Friday:

17:30 Registration
18:30 Opening 
20:00 Brainstorming
21:00 Idea Pitching
21:30 Start Coding

Saturday:

9:30 Breakfast
11:00 Mentor & HR Meetings
11:30 Idea Pitching Pt. 2
12:00 Mentor & HR Meetings
13:30 Lunch
14:30 Mentorship + Coding
19:30 Dinner
20:30 Coding

Sunday:

9:30 Breakfast
10:30 Coding
13:00 Presentations Submission Deadline
13:00 Lunch
(right after they submit the presentations they have lunch yes)
14:30 Presentations Begin
19:00 Award Ceremony

**Comment by savinadd** [comment]
I have changed the layout to either a horizontal row with three columns or one column with three rows depending on screen width, @annakukova and I discussed it and we think it would look better this way. @SuelaCark @annakukova, are we sticking to the idea of green lines between the days that @SuelaCark suggested? in my opinion, i think it might make the grading criteria and the schedule section look very similar in design

**Comment by annakukova** [comment]
It looks nice and clean to me as it is right now, but if we do decide to have the lines in between, I would suggest that they're only for the desktop version. Responsive looks nice and the headings for each day act as separators so IMO no need of them for mobile.
