### ISSUE TITLE
Make HackAUBG letters animation slower and make journey section cards more rounded

### ISSUE THREAD

**Issue by Aleks1908** [AUBGTheHUB/spa-website-2022#317]

**Comment by asynchroza** [comment]
Can you as well change the font and/or the boldness of the text below 
<img width="725" alt="image" src="https://user-images.githubusercontent.com/104720011/221562503-08754c62-21ed-4754-b7a8-f7ce6c8de29d.png">

Also it seems that the font is a bit small when viewed from a phone.
