### ISSUE TITLE
Hide mentors for now

### ISSUE THREAD

**Issue by SuelaCark** [AUBGTheHUB/spa-website-2022#324]
Since the PR Department has not provided us with the pictures of the Mentors for the hackathon yet, we will need to remove/hide the Mentors pictures/section for now. Instead we will have something written like 'Mentors coming soon...' and later on we can unhide the mentors section/images.

**Comment by asynchroza** [comment]
Delete placeholders from Admin Panel?

**Comment by SuelaCark** [comment]
> Delete placeholders (mocked mentors and judges) from Admin Panel? Wdyt?
> 
> If no mentors are fetched, component won't render

I thought of commenting out the code partially, but this would be easier. Then we will just add a text: "Mentors coming soon..."  and change it back when we have the mentors.

**Comment by asynchroza** [comment]
> > Delete placeholders (mocked mentors and judges) from Admin Panel? Wdyt?
> > If no mentors are fetched, component won't render
> 
> I thought of commenting out the code partially, but this would be easier. Then we will just add a text: "Mentors coming soon..." and change it back when we have the mentors.

done

**Comment by SuelaCark** [comment]
@asynchroza I verified it, but I will keep this ticket open so we can add the "Mentors coming soon..." text. I will assign this issue to a frontender.
