### ISSUE TITLE
Update email template with new text from marketing

### ISSUE THREAD

**Issue by IvanObreshkov** [AUBGTheHUB/spa-website-2022#375]
## Brief description:

HTML email template that is sent to every new registered participant via the Google Cloud function integrated in the register endpoint in the API.

## How to achieve it:

Use [this](https://github.com/AUBGTheHUB/website-2021/blob/3e5acfc89cd27b529da295748805838af42b1314/packages/api/src/templates/confirmation.html) template or create a new one, and add it to the function for sending the email located in the register controller in the `packages/api/controllers` folder.

**Comment by SuelaCark** [comment]
@DemonHashira The text from the marketing department is as follows:

Thank you for registering for HackAUBG 5.0! 

Before the hackathon starts, there are a few important things:

To ensure you stay in the loop, we will invite you to join the Official HackAUBG 5.0 Facebook group. That is where we'll share all the latest updates and instructions about the event. 

What's more, each team will have their very own facilitator from The Hub to guide you through the hackathon. They'll be your point of contact for any questions or concerns you may have and will even help you find new teammates if needed.

We're thrilled to have you on board and can't wait to meet you!
- The Hub AUBG

**Comment by asynchroza** [comment]
> @DemonHashira The text from the marketing department is as follows:
> 
> Thank you for registering for HackAUBG 5.0!
> 
> Before the hackathon starts, there are a few important things:
> 
> To ensure you stay in the loop, we will invite you to join the Official HackAUBG 5.0 Facebook group. That is where we'll share all the latest updates and instructions about the event.
> 
> What's more, each team will have their very own facilitator from The Hub to guide you through the hackathon. They'll be your point of contact for any questions or concerns you may have and will even help you find new teammates if needed.
> 
> We're thrilled to have you on board and can't wait to meet you! -The Hub AUBG

@SuelaCark is the group created? I don't think it's a good idea to send this email without actually providing the Facebook link.
