### ISSUE TITLE
[ADMIN PANEL] S3 styling update

### ISSUE THREAD

**Issue by asynchroza** [AUBGTheHUB/spa-website-2022#414]
Image Management section in admin panel requires a UI overhaul. 

When listing the images, they should have copy url and delete buttons. Delete buttons should ask whether the user is sure before deletion.

**Comment by asynchroza** [comment]
Nice work on this @SuelaCark ! 

Do you think we could probably implement a popover which notifies users that they've successfully copied the image url? You may use [react bootstrap](https://react-bootstrap.github.io/components/overlays/) for this since we already have this implemented in the project.

**Comment by asynchroza** [comment]
@SuelaCark I see some work has been done here? Do you think we can reuse your work?

@Aleks1908 care to give it a look?

**Comment by SuelaCark** [comment]
> @SuelaCark I see some work has been done here? Do you think we can reuse your work?
> 
> @Aleks1908 care to give it a look?

I do believe that what I had worked on previously for this ticket really helped on improving the understanding of the UI/UX part of the admin panel. If we have some time in the future, we should be trying to fix the admin panel's usability and general design organization, even if its still going to be used only from the Dev department.
